version: "3"
services:
  app1:
    image: ethereum/client-go
    entrypoint: /bin/sh
    tty: true
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ./geth:/geth