package main

import (
	"context"
	"log"
	"net/http"

	"connectrpc.com/connect"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	// generated by protoc-gen-go
	contract_connect_v1 "github.com/somasekimoto/geth-demo/gocode/protobuf/contract_connector/v1"
	"github.com/somasekimoto/geth-demo/gocode/protobuf/contract_connector/v1/contract_connectorv1connect"
	// generated by protoc-gen-connect-go
)

type ContractConnectServer struct{}

func (s *ContractConnectServer) ContractConnect(
	ctx context.Context,
	req *connect.Request[contract_connect_v1.ContractConnectRequest],
) (*connect.Response[contract_connect_v1.ContractConnectResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&contract_connect_v1.ContractConnectResponse{
		Result: "Hello, world!",
	})
	res.Header().Set("Contract-Connect-Version", "v1")
	return res, nil
}

func server() http.Handler {
	mux := http.NewServeMux()
	mux.Handle(contract_connectorv1connect.NewContractConnectorServiceHandler(&ContractConnectServer{}))
	return mux
}

func main() {
	mux := server()
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
